services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  cv:
    image: ghcr.io/pavletto/cv:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cv.entrypoints=web"
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    command:
      - "--interval"
      - "30"
      - "--label-enable"
      - "--rolling-restart"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock